@startuml "Implementasi"
package "conn" {
  [TCPServer] -down-> [TCP]
  [TCPClient] -down-> [TCP]
  [TLS] -right-> [TCP]
  [TLS] -left-> [Handshake]
}

package "crypto" {
  [DynamicAES]
  [MAC]
  [DynamicAES] -> [HenonSineMap]
  [KeyGenerator]
}

package "socket" {
  [Socket] 
}

package "secret" {
  [Digest Comparator]
}

package "pycryptodome" {
  [AES]
  [HMAC]
}

package "app" {
  [Main]
}

package "pathlib" {
  [Path]
}

package "util" {
}

Main -down-> Path
Main -down-> TCPServer
Main -down-> TCPClient
Main -down-> TLS
TLS -down-> DynamicAES
TCP -> Socket
Handshake -> KeyGenerator
Handshake -down-> MAC
TLS -down-> MAC
DynamicAES -down-> AES
MAC -down-> HMAC
MAC -down-> [Digest Comparator]
TLS -down-> util

@enduml