@startuml ""

start

:Simpan State Awal;

repeat ;
  :Baca Blok Baru;
  :Enkripsi Blok;

  if (Enkripsi Berhasil) then (Tidak)
    :Kembalikan State Awal;
    stop;
  endif

  :Update Kunci Blok dan Counter;

repeat while (Masih ada blok lainnya?) is (Ya) not (Tidak)

:Hitung MAC;

stop

@enduml