@startuml ""

start

:Simpan State Awal;

:Hitung MAC;
:Append Nilai MAC pada plaintext;

repeat ;
  :Baca Blok Baru;
  :Enkripsi Blok;

  if (Enkripsi Berhasil) then (Tidak)
    :Kembalikan State Awal;
    stop;
  endif

  :Update Kunci Blok dan Counter;

repeat while (Masih ada blok lainnya?) is (Ya) not (Tidak)

stop

@enduml